version: "3"

tasks:
  build:
    desc: Build Go binary
    cmds:
    - go build -o bin/kutego-api internal/main.go
  run: 
    desc: Run http server directly (without build)
    cmds:
    - go run internal/main.go

  swagger:validate:
    desc: Validate Swagger spec
    cmds:
    - cmd: |
        swagger validate ./pkg/swagger/swagger.yml
  
  swagger:serve:
    desc: Serve swagger UI
    cmds:
    - cmd: |
        swagger serve ./pkg/swagger/swagger.yml
  
  # docker:swagger:validate:
  #   desc: Validate Swagger spec
  #   cmds:
  #   - cmd: |
  #       docker run -it --rm \
  #       --user $(id -u):$(id -g) \
  #       -e GOPATH=$(go env GOPATH):/go \
  #       -v $HOME:$HOME \
  #       -w $(pwd) quay.io/goswagger/swagger validate ./pkg/swagger/swagger.yml
  ## Doesn't work for now because I don't find how to serve on MacOS host from docker desktop
  ## `host.docker.internal` fail :'(
  # docker:swagger:serve:
  #   desc: Run swagger
  #   cmds:
  #   - cmd: |
  #       docker run --rm \
  #       --user $(id -u):$(id -g) \
  #       -e GOPATH=$(go env GOPATH):/go \
  #       -v $HOME:$HOME \
  #       -w $(pwd) quay.io/goswagger/swagger serve ./pkg/swagger/swagger.yml --no-open


