// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CheckHealthOKCode is the HTTP code returned for type CheckHealthOK
const CheckHealthOKCode int = 200

/*CheckHealthOK OK message

swagger:response checkHealthOK
*/
type CheckHealthOK struct {
}

// NewCheckHealthOK creates CheckHealthOK with default headers values
func NewCheckHealthOK() *CheckHealthOK {

	return &CheckHealthOK{}
}

// WriteResponse to the client
func (o *CheckHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
