// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Gopher gopher
//
// swagger:model Gopher
type Gopher struct {

	// name
	// Example: my-gopher
	Name string `json:"name,omitempty"`

	// path
	// Example: my-gopher.png
	Path string `json:"path,omitempty"`

	// url
	// Example: https://raw.githubusercontent.com/scraly/gophers/main/arrow-gopher.png
	URL string `json:"url,omitempty"`
}

// Validate validates this gopher
func (m *Gopher) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gopher based on context it is used
func (m *Gopher) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Gopher) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Gopher) UnmarshalBinary(b []byte) error {
	var res Gopher
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
