# name: CloudRun

- name: Deploy to Cloud Run
  id: deploy
  uses: google-github-actions/deploy-cloudrun@main
  with:
    service: kutego-api 
    image: eu.gcr.io/${{ secrets.PROJECT }}/kutego-api:0.1.2
    credentials: ${{ secrets.GCP_SA_KEY }}

- name: Use Output
  run: curl "${{ steps.deploy.outputs.url }}"


# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Dagger
#         uses: dagger/dagger-action@v1
#         with:
#           age-key: ${{ secrets.DAGGER_AGE_KEY }}
#           args: up -e gcpcloudrun