name: CloudRun-Prod

env:
  REGION: europe-west1
  SERVICE: kutego-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and Push Container
        run: |-
          docker build -t eu.gcr.io/${{ secrets.PROJECT }}/${{ env.SERVICE }}:${{  github.sha }} .
          docker push eu.gcr.io/${{ secrets.PROJECT }}/${{ env.SERVICE }}:${{  github.sha }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          image: eu.gcr.io/${{ secrets.PROJECT }}/kutego-api:${{  github.sha }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: ${{ env.REGION }}

      # - name: Use Output
      #   run: curl "${{ steps.deploy.outputs.url }}/gophers"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Dagger
#         uses: dagger/dagger-action@v1
#         with:
#           age-key: ${{ secrets.DAGGER_AGE_KEY }}
#           args: up -e gcpcloudrun